name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: git submodule
      run: git submodule update --init

    - name: Install dependencies
      run: |
       sudo apt-get -qq update
       sudo apt-get install -yq bison libpng-dev pkg-config
       git clone https://github.com/gbdev/rgbds.git
       cd rgbds
       make
       sudo make install
       cd ..
    - name: Build rom
      run: make
    - name: Archive build rom
      uses: actions/upload-artifact@v4
      with:
        name: rom
        path: bin/*
